"""init_db

Revision ID: 0f83098dbbd3
Revises: 
Create Date: 2021-05-10 17:19:51.692642

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f83098dbbd3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retailer_rewards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_retailer_rewards_id"), "retailer_rewards", ["id"], unique=False)
    op.create_index(op.f("ix_retailer_rewards_slug"), "retailer_rewards", ["slug"], unique=True)
    op.create_table(
        "campaign",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DRAFT", "CANCELLED", "ENDED", name="campaignstatuses"),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("retailer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["retailer_id"], ["retailer_rewards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaign_id"), "campaign", ["id"], unique=False)
    op.create_index(op.f("ix_campaign_slug"), "campaign", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campaign_slug"), table_name="campaign")
    op.drop_index(op.f("ix_campaign_id"), table_name="campaign")
    op.drop_table("campaign")
    op.drop_index(op.f("ix_retailer_rewards_slug"), table_name="retailer_rewards")
    op.drop_index(op.f("ix_retailer_rewards_id"), table_name="retailer_rewards")
    op.drop_table("retailer_rewards")
    # ### end Alembic commands ###
