"""RewardRule table

Revision ID: e7ead84a0d44
Revises: 6435085f69d3
Create Date: 2021-06-16 14:45:53.449092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7ead84a0d44"
down_revision = "6435085f69d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reward_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("reward_goal", sa.Integer(), nullable=False),
        sa.Column("voucher_type_slug", sa.String(length=32), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaign.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reward_rule_id"), "reward_rule", ["id"], unique=False)
    op.create_index(op.f("ix_reward_rule_voucher_type_slug"), "reward_rule", ["voucher_type_slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reward_rule_voucher_type_slug"), table_name="reward_rule")
    op.drop_index(op.f("ix_reward_rule_id"), table_name="reward_rule")
    op.drop_table("reward_rule")
    # ### end Alembic commands ###
