"""campaign start and end

Revision ID: f00aa9d2ba8d
Revises: e7ead84a0d44
Create Date: 2021-06-17 12:45:12.898435

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f00aa9d2ba8d"
down_revision = "e7ead84a0d44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("campaign", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("campaign", sa.Column("end_date", sa.DateTime(), nullable=True))
    op.execute("UPDATE campaign SET start_date = created_at")
    op.alter_column("campaign", "start_date", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaign", "end_date")
    op.drop_column("campaign", "start_date")
    # ### end Alembic commands ###
